# This is a basic workflow to help you get started with Actions

name: Latex

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths: 
      - "**.tex"
      - .github/workflows/latex.yml
  pull_request:
    branches: [ "main" ]
    paths: ["**.tex"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-latex"
  build-latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            base:
              - 'Comm*.tex'
            design:
              - 'Design/**'
            dp:
              - 'DevelopmentPlan/**'
            ha:
              - 'HazardAnalysis/**'
            psag:
              - 'ProblemStatementAndGoals/**'
            reflect:
              - 'Reflection/**'
            srs:
              - 'SRS/**'
            ug:
              - 'UserGuide/**'
            vnvp:
              - 'VnVPlan/**'
            vnvr:
              - 'VnVReport/**'
        

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: pdflatex Common
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.base == 'true' }}
        with:
          root_file: Common.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex Comments
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.base == 'true' }}
        with:
          root_file: Comments.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex MG
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.design == 'true' }}
        with:
          root_file: Design/MG/MG.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex MIS
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.design == 'true' }}
        with:
          root_file: Design/MIS/MIS.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      
      - name: pdflatex DevelopmentPlan
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.dp == 'true' }}
        with:
          root_file: DevelopmentPlan/DevelopmentPlan.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex ha
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.ha == 'true' }}
        with:
          root_file: HazardAnalysis/HazardAnalysis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex psag
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.psag == 'true' }}
        with:
          root_file: ProblemStatementAndGoals/ProblemStatement.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex reflect
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.reflect == 'true' }}
        with:
          root_file: Reflection/Reflection.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex ca
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.srs == 'true' }}
        with:
          root_file: SRS/CA.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex srs-faq
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.srs == 'true' }}
        with:
          root_file: SRS/SRS-FAQ.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex srs
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.srs == 'true' }}
        with:
          root_file: SRS/SRS.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex userguide
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.ug == 'true' }}
        with:
          root_file: UserGuide/UserGuide.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex VnVPlan
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.vnvp == 'true' }}
        with:
          root_file: VnVPlan/VnVPlan.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: pdflatex VnVReport
        uses: dante-ev/latex-action@latest
        if: ${{ steps.filter.outputs.vnvr == 'true' }}
        with:
          root_file: VnVReport/VnVReport.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
      - name: Push new .pdfs
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "Generated new .pdf files in docs subfolders"
          git push
