# Uses:
# https://github.com/marketplace/actions/push-to-status-check-protected-branches

name: Update Documentation Branches after Merge to Main
on:
  # Triggers the workflow pull request events but only for the "main" branch
  push:
    branches: 
      - "main" 
    paths: 
      - "**.tex"
      - "**.yml"
  pull_request:
    types:
      - closed
    branches: 
      - "main" 
    paths: 
      - "**.tex"
      
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix: 
        branch: ["Documentation/DD", "Documentation/DEMO", "Documentation/DP", "Documentation/EXPODEMO", "Documentation/FINALDEMO", "Documentation/FINALDOC", "Documentation/HA", "Documentation/POC", "Documentation/PSAG", "Documentation/SRS", "Documentation/VNVP", "Documentation/VNVR"]
    steps:
      - name: 'Checkout main'
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: 'Checkout ${{ matrix.branch }}'
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Sync ${{ matrix.branch }} with main
        run: |
          echo "Merging main into ${{ matrix.branch }}"
          git fetch origin main --depth 1
          git merge --ff-only --no-edit -v origin/main
      
      - name: Pushing to the protected branch ${{ github.ref_name }}
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.AUTO_PAT }}
          branch: ${{ matrix.branch }}
          unprotect_reviews: true
        continue-on-error: true
