# Uses:
# https://github.com/marketplace/actions/push-to-status-check-protected-branches

name: Update Documentation Branches after Merge to Main
on:
  # Triggers the workflow pull request events but only for the "main" branch
  push:
    branches: 
      - "main" 
    paths: 
      - "**.tex"
      - "**.yml"
  pull_request:
    types:
      - closed
    branches: 
      - "main" 
    paths: 
      - "**.tex"
      
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        branch: ["Documentation/DD", "Documentation/DEMO", "Documentation/DP", "Documentation/EXPODEMO", "Documentation/FINALDEMO", "Documentation/FINALDOC", "Documentation/HA", "Documentation/POC", "Documentation/PSAG", "Documentation/SRS", "Documentation/VNVP", "Documentation/VNVR"]
    steps:
      - uses: actions/checkout@v3

      - name: Sync main with Documentation branches
        run: |
          echo "Merging main into ${{ matrix.branch }}"
          git checkout ${{ matrix.branch }}
          git merge main
          git add -A
          git commit -m "Merging main into ${{ matrix.branch }}"
      
      - name: Pushing to the protected branch ${{ github.ref_name }}
        uses: CasperWA/push-protected@v2
        if: ${{ success() && github.event.pull_request.merged == true }}
        with:
          token: ${{ secrets.AUTO_PAT }}
          branch: ${{ matrix.branch }}
          unprotect_reviews: true
